### ISSUE TITLE
Closed or open group?

### ISSUE THREAD

**Issue by Boostem** [fdac20/SpotifySong#1]
Hello, 
My name is Hudson and I have not fully found my group. As someone who always looks into my own music statistics with last.fm and other spotify api websites your project looked super interesting and a very fun project. I have python and JS experience, which is what I assume you guys might use for this. 

Are you guys open to one more member or are you guys keeping your group closed? I understand wanting to keep your group at 4!

**Comment by boostem** [comment]
Closed due to finding a group, thank you nonetheless!
